require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: '3.1'
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/ParameterLists:
  Max: 10

Metrics/MethodLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 45

Metrics/PerceivedComplexity:
  Max: 45

Metrics/BlockLength:
  Max: 100

Style/MultipleComparison:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Layout/LineLength:
  AllowedPatterns: ['\A\s*#']

Metrics/AbcSize:
  Max: 100

Metrics/ModuleLength:
  Max: 1000

Metrics/ClassLength:
  Max: 1000

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleExpectations:
  Max: 25

RSpec/ExampleLength:
  Max: 500

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/AnyInstance:
  Enabled: false

Metrics/BlockNesting:
  Max: 5
